# Generated by Django 5.0.2 on 2026-08-18 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0002_administradores_alumnos_maestros_delete_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosAcademicos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(choices=[('congreso', 'Congreso'), ('conferencia', 'Conferencia'), ('taller', 'Taller'), ('seminario', 'Seminario'), ('feria', 'Feria'), ('curso', 'Curso'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrido', 'Híbrido')], default='presencial', max_length=20)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('enlace', models.URLField(blank=True, max_length=500, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_academicos_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clave_materia', models.CharField(max_length=50, unique=True)),
                ('nombre_materia', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creditos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('semestre', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
